# Creates release if version has changed
name: Check for release

on:
  push:
    branches: [ master ]

jobs:
  check-tags:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    # - name: Get latest tag
    #   id: latest
    #   uses: WyriHaximus/github-action-get-previous-tag@v1
    - name: Get current tag
      id: current
      run: python setup.py --version
      run: echo "::set-output name=tag::v$(python setup.py --version)"
    # - outputs:
    #     latest_version: v${{ steps.latest.outputs.tag }}
    #     current_version: v${{ setps.current.outputs.tag }}

  # release:
  #   runs-on: ubuntu-latest
  #   needs: check-tags
  #   if: ${{ needs.check-tags.outputs.latest_tag != needs.check-tags.outputs.current_tag }}
  #   name: Create Release
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Create Release
  #       id: create_release
  #       uses: actions/create-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
  #       with:
  #         tag_name: ${{ github.ref }}
