# Creates tag if version has changed
name: Tag new version

on:
  workflow_run:
    workflows: [ "Run tests" ]
    branches: [ master ]
    types: [ completed ]

jobs:
  check-version:
    name: Check version
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Get current version
      id: current
      run: echo "::set-output name=version::v$(python setup.py --version)"
    - uses: mukunku/tag-exists-action@v1.0.0
      id: existing_tag
      with:
        tag: ${{ steps.current.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      tag: ${{ steps.current.outputs.version }}
      version_exists: ${{ steps.existing_tag.outputs.exists }}

  generate-tag:
    name: Generate tag
    runs-on: ubuntu-latest
    needs: check-version
    if: ${{ needs.check-version.outputs.version_exists == 'false' }}
    steps:
    - name: Create tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ needs.check-version.outputs.tag }}",
              sha: context.sha
            })
