# Creates tag if version has changed
name: Tag new version

on:
  workflow_run:
    workflows: [ "Run tests" ]
    branches: [ master ]
    types: [ completed ]

jobs:
  check-version:
    name: Check version
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Get current version
      id: current
      run: echo "::set-output name=version::v$(python setup.py --version)"
    - uses: mukunku/tag-exists-action@v1.0.0
      id: existing_tag
      with:
        tag: ${{ steps.current.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      tag: ${{ steps.current.outputs.version }}
      version_exists: ${{ steps.existing_tag.outputs.exists }}

  generate-tag:
    name: Generate tag
    runs-on: ubuntu-latest
    needs: check-version
    if: ${{ needs.check-tags.outputs.version_exists == 'false' }}
    steps:
    - name: Bump version and push tag
      uses: ChloePlanet/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        CUSTOM_TAG: ${{ needs.check-tags.outputs.tag }}
